services:
  php-fpm:
    container_name: ${APP_NAME}-php-fpm
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./../:/var/www/

  nginx:
    container_name: ${APP_NAME}-nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  rabbitmq:
    image: rabbitmq:3.13.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
      - 5672:5672
